account_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
name = "vod_timing"
type = "webpack"
workers_dev = true
site = { bucket = "./public" }
compatibility_date = "2021-12-13"
kv_namespaces = [ 
	{ binding = "tokens", preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
]

[vars]
twitch_username = "username"
twitch_parser_url = "second_backend_url"


[miniflare]
host = "127.0.0.1"                 # --host
port = 8787                        # --port
watch = true                       # --watch
live_reload = true                 # --live-reload
debug = true

# [secrets]
# clientId
# clientSecret
